#!/usr/bin/env bash


gem install rvm bundler what_methods dbf unicorn eventmachine bugs_bunny\
    hirb symbolize rubocop rspec rspec-rails thin nokogiri pry redis ghi\
    wirble sidekiq awesome_print jeweler what_methods did_you_mean git-up


# rvm install ree
# rvm install rbx
# rvm install 1.9.2
